apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: artimation
spec:
  brokerProperties: {}
  brokerSpec:
    brokerPodSpec:
      containers:
      - name: artimation
        image: lucabarze/artimation:0.2
        securityContext:
          privileged: true
      volumes:
      - name: dev
        hostPath:
          path: /dev
  capacity: 1
  discoveryHandler:
    discoveryDetails: |
      udevRules:
      - SUBSYSTEM=="video4linux", KERNEL=="video[0-9]*"
    name: udev

