apiVersion: apps/v1
kind: Deployment
metadata:
  name: artimation-deployment
  labels:
    app: artimation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: artimation
  template:
    metadata:
      labels:
        app: artimation
    spec:
      containers:
      - name: artimation
        image: lucabarze/artimation:1.0
        ports:
        - containerPort: 8000
